version: '3'

networks:
  stibel_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PROJECT_NETWORK_SUBNET}
          gateway: ${PROJECT_NETWORK_GATEWAY}

services:
  mysql:
    build:
      context: ./environment/mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    image: "${PROJECT_NAME}_${MYSQL_IMAGE_NAME}:${IMAGE_TAR}"
    restart: always
    container_name: "${PROJECT_NAME}_${MYSQL_CONTAINER_NAME}"
    ports:
      - '${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}'
    networks:
      stibel_net:
        ipv4_address: ${MYSQL_HOST_IP}
  nginx:
    image: nginx
    container_name: "${PROJECT_NAME}_${NGINX_CONTAINER_NAME}"
    restart: always
    ports:
      - '${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}'
    volumes:
      - ./environment/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./environment/nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
      - ./data/nginx/html:/usr/share/nginx/html:rw
    networks:
      stibel_net:
        ipv4_address: ${NGINX_HOST_IP}
  webserver:
    build:
      context: ./environment/webserver
      dockerfile: Dockerfile
      args:
        - MYSQL_HOST_IP=${MYSQL_HOST_IP}
        - MYSQL_CONTAINER_PORT=${MYSQL_CONTAINER_PORT}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    image: "${PROJECT_NAME}_${WEBSERVER_IMAGE_NAME}:${IMAGE_TAR}"
    restart: always
    container_name: "${PROJECT_NAME}_${WEBSERVER_CONTAINER_NAME}"
    ports:
      - '${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}'
    networks:
      stibel_net:
        ipv4_address: ${WEBSERVER_HOST_IP}