version: '3.1'

services:
  webserver:
    image: klc407073648/centos_build_lib:v3.0
    container_name: "${STIBEL_CONTAINER_NAME}"
    restart: always
    ports:
      - '${HOST_MACHINE_STIBEL_PORT}:9950'
    volumes:
      - ../../StiBel:/home/tools/StiBel
