version: '3.1'

services:
  nginx:
    image: nginx
    container_name: "${WEB_CONTAINER_NAME}"
    restart: always
    ports:
      - '${HOST_MACHINE_WEB_PORT}:${WEB_CONTAINER_PORT}'
    volumes:
      - ./environment/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./environment/conf.d:/etc/nginx/conf.d
      - ./environment/html:/usr/share/nginx/html:rw
