version: '3'

services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    container_name: stibel_jenkins_0
    ports:
      - '8090:8080'
      - '50000:50000'
    volumes:
      - ./data/:/var/jenkins_home