version: '3.1'

services:
  consul:
    build:
      context: ./environment
      dockerfile: Dockerfile
      args:
        - CONSUL_DATA_DIR=${CONSUL_DATA_DIR}
    image: "${CONSUL_IMAGE_NAME}:${CONSUL_IMAGE_TAR}"
    restart: always
    container_name: "${CONSUL_CONTAINER_NAME}"
    ports:
       - "${CONSUL_HTTP_PORT}:8500"
    #  - "${CONSUL_SERVER_PORT}:8300"
    #  - "${CONSUL_SERF_LAN_PORT}:8301"
    #  - "${CONSUL_SERF_WAN_PORT}:8302"
    #  - "${CONSUL_HTTP_PORT}:8500"
    #  - "${CONSUL_DNS_PORT}:8600"
    #volumes:
    #  - ./environment/data:${CONSUL_DATA_DIR}
